"""environmental data foundation: sources, stations, measurements

Revision ID: 5f6a5f26cd25
Revises: 1adf6d262316
Create Date: 2026-09-22 01:27:27.293321

"""
from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f6a5f26cd25'
down_revision: Union[str, None] = '1adf6d262316'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('license', sa.String(length=256), nullable=False),
    sa.Column('homepage_url', sa.String(length=512), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expected_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('stale_after_seconds', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_message', sa.String(length=1024), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_sources_code'), 'data_sources', ['code'], unique=True)
    op.create_table('stations',
    sa.Column('data_source_id', sa.UUID(), nullable=False),
    sa.Column('external_code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('city', sa.String(length=128), nullable=False),
    sa.Column('river_name', sa.String(length=128), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_source_id', 'external_code', name='uq_station_source_external_code')
    )
    # NOTE: no explicit op.create_index() for the geometry column here —
    # GeoAlchemy2's Geometry type manages its own GIST spatial index via a
    # DDL event fired on op.create_table() above (spatial_index=True is the
    # type's default). Adding an explicit create_index for it as well
    # raises "relation already exists" (confirmed while testing this
    # migration against a genuinely fresh schema).
    op.create_table('measurements',
    sa.Column('station_id', sa.UUID(), nullable=False),
    sa.Column('variable', sa.String(length=32), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_backfill', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'variable', 'observed_at', name='uq_measurement_station_variable_time')
    )
    op.create_index(op.f('ix_measurements_observed_at'), 'measurements', ['observed_at'], unique=False)
    op.create_index(op.f('ix_measurements_variable'), 'measurements', ['variable'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_measurements_variable'), table_name='measurements')
    op.drop_index(op.f('ix_measurements_observed_at'), table_name='measurements')
    op.drop_table('measurements')
    op.drop_table('stations')  # drops the GeoAlchemy2-managed spatial index along with the table
    op.drop_index(op.f('ix_data_sources_code'), table_name='data_sources')
    op.drop_table('data_sources')
    # ### end Alembic commands ###
