"""P3: situation briefs table + AI scheduling job state

Revision ID: 6e15941eda66
Revises: 7b58fd62314c
Create Date: 2026-09-23 23:04:31.624984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e15941eda66'
down_revision: Union[str, None] = '7b58fd62314c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('situation_briefs',
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('triggered_by', sa.String(length=16), nullable=False),
    sa.Column('situation', sa.String(length=16), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('drivers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('zones_to_watch', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('limitations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risk_score_snapshot', sa.Float(), nullable=False),
    sa.Column('risk_severity_snapshot', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_situation_briefs_generated_at'), 'situation_briefs', ['generated_at'], unique=False)
    op.add_column('ai_provider_config', sa.Column('last_analysis_attempt_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ai_provider_config', sa.Column('last_analysis_error', sa.String(length=512), nullable=True))
    # server_default='0' is required here (unlike the model's Python-side
    # default=0): this ALTER TABLE ADD COLUMN ... NOT NULL runs against the
    # already-existing ai_provider_config singleton row from every prior
    # deployment (created by get_or_create_ai_config back in P0) — without a
    # server-side default, backfilling that existing row would fail.
    op.add_column('ai_provider_config', sa.Column('requests_today', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('ai_provider_config', sa.Column('requests_today_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_provider_config', 'requests_today_date')
    op.drop_column('ai_provider_config', 'requests_today')
    op.drop_column('ai_provider_config', 'last_analysis_error')
    op.drop_column('ai_provider_config', 'last_analysis_attempt_at')
    op.drop_index(op.f('ix_situation_briefs_generated_at'), table_name='situation_briefs')
    op.drop_table('situation_briefs')
    # ### end Alembic commands ###
