"""p4 scenario simulator ai explanation cooldown

Revision ID: fb7c98e7340a
Revises: 6e15941eda66
Create Date: 2026-09-23 23:43:03.640002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb7c98e7340a'
down_revision: Union[str, None] = '6e15941eda66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_provider_config', sa.Column('last_scenario_explanation_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_provider_config', 'last_scenario_explanation_at')
    # ### end Alembic commands ###
