"""countries and cities reference tables

Revision ID: fccdd527a80f
Revises: 5f6a5f26cd25
Create Date: 2026-09-22 02:48:36.136962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fccdd527a80f'
down_revision: Union[str, None] = '5f6a5f26cd25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('iso2', sa.String(length=2), nullable=False),
    sa.Column('iso3', sa.String(length=3), nullable=False),
    sa.Column('label_en', sa.String(length=128), nullable=False),
    sa.Column('label_fr', sa.String(length=128), nullable=False),
    sa.Column('label_es', sa.String(length=128), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iso2'),
    sa.UniqueConstraint('iso3')
    )
    op.create_table('cities',
    sa.Column('country_id', sa.UUID(), nullable=False),
    sa.Column('label_en', sa.String(length=128), nullable=False),
    sa.Column('label_fr', sa.String(length=128), nullable=False),
    sa.Column('label_es', sa.String(length=128), nullable=False),
    sa.Column('default_lon', sa.Float(), nullable=False),
    sa.Column('default_lat', sa.Float(), nullable=False),
    sa.Column('default_zoom', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_id', 'label_en', name='uq_city_country_label_en')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cities')
    op.drop_table('countries')
    # ### end Alembic commands ###
